name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/noto-books.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp.png
    - assets/page-1/images/ic-baseline-book.png
    - assets/page-1/images/black-simple-monoline-real-estate-service-logo-1.png
    - assets/page-1/images/mdi-user-circle.png
    - assets/page-1/images/mdi-password.png
    - assets/page-1/images/fluent-emoji-flat-books.png
    - assets/page-1/images/whatsapp-image-2023-03-26-at-1416-2.png
    - assets/page-1/images/material-symbols-wifi.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-3.png
    - assets/page-1/images/material-symbols-wifi-8aV.png
    - assets/page-1/images/download-1.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-bpD.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-1.png
    - assets/page-1/images/auto-group-tuw3.png
    - assets/page-1/images/ion-arrow-back-outline.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-WTs.png
    - assets/page-1/images/mdi-user-circle-m69.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-3.png
    - assets/page-1/images/download-3.png
    - assets/page-1/images/download-2.png
    - assets/page-1/images/ic-baseline-book-JxH.png
    - assets/page-1/images/emojione-books.png
    - assets/page-1/images/openmoji-star.png
    - assets/page-1/images/mdi-user-circle-feH.png
    - assets/page-1/images/openmoji-star-Q1w.png
    - assets/page-1/images/emojione-v1-books.png
    - assets/page-1/images/material-symbols-home.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-3-Lky.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-2.png
    - assets/page-1/images/auto-group-ijtm.png
    - assets/page-1/images/line-7.png
    - assets/page-1/images/download-3-rs3.png
    - assets/page-1/images/ic-baseline-book-cLy.png
    - assets/page-1/images/material-symbols-wifi-mv1.png
    - assets/page-1/images/material-symbols-wifi-fsF.png
    - assets/page-1/images/material-symbols-home-zb3.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-5gM.png
    - assets/page-1/images/material-symbols-wifi-Fyj.png
    - assets/page-1/images/material-symbols-search-rounded.png
    - assets/page-1/images/material-symbols-home-AgR.png
    - assets/page-1/images/mdi-user-circle-fH3.png
    - assets/page-1/images/line-9.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-CmP.png
    - assets/page-1/images/ion-arrow-back-outline-MAR.png
    - assets/page-1/images/material-symbols-wifi-Mn1.png
    - assets/page-1/images/material-symbols-search-rounded-77P.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-1.png
    - assets/page-1/images/ic-baseline-book-7ER.png
    - assets/page-1/images/material-symbols-search-rounded-BmK.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-wHs.png
    - assets/page-1/images/material-symbols-search-rounded-mjP.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-2-LbT.png
    - assets/page-1/images/material-symbols-wifi-uyK.png
    - assets/page-1/images/material-symbols-home-3qs.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-Hnh.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-1-5Eh.png
    - assets/page-1/images/auto-group-e6db.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-9bo.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-rxh.png
    - assets/page-1/images/ic-baseline-book-m21.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2.png
    - assets/page-1/images/line-6.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1.png
    - assets/page-1/images/line-5.png
    - assets/page-1/images/download-4.png
    - assets/page-1/images/line-5-cam.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-vbT.png
    - assets/page-1/images/openmoji-star-4xZ.png
    - assets/page-1/images/download-4-wow.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-3-Ko7.png
    - assets/page-1/images/material-symbols-home-LPK.png
    - assets/page-1/images/line-6-Kny.png
    - assets/page-1/images/line-5-tBb.png
    - assets/page-1/images/line-7-H8V.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-wfX.png
    - assets/page-1/images/material-symbols-wifi-XjX.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-6i5.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-3-Upy.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-1-GVF.png
    - assets/page-1/images/material-symbols-search-rounded-YS5.png
    - assets/page-1/images/material-symbols-search-rounded-ggh.png
    - assets/page-1/images/ion-arrow-back-outline-DfF.png
    - assets/page-1/images/material-symbols-wifi-en5.png
    - assets/page-1/images/ic-baseline-book-iW5.png
    - assets/page-1/images/line-9-Kg5.png
    - assets/page-1/images/ion-arrow-back-outline-Xb7.png
    - assets/page-1/images/material-symbols-home-4mP.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-8YH.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-ZSZ.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-5oX.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-jFo.png
    - assets/page-1/images/material-symbols-wifi-PUm.png
    - assets/page-1/images/material-symbols-home-Rrh.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-2-xbj.png
    - assets/page-1/images/material-symbols-search-rounded-JL9.png
    - assets/page-1/images/rectangle-1.png
    - assets/page-1/images/line-8.png
    - assets/page-1/images/material-symbols-wifi-TpV.png
    - assets/page-1/images/material-symbols-wifi-8RP.png
    - assets/page-1/images/material-symbols-home-ov9.png
    - assets/page-1/images/rectangle-1-8gq.png
    - assets/page-1/images/material-symbols-search-rounded-JyF.png
    - assets/page-1/images/ic-baseline-book-hnR.png
    - assets/page-1/images/download-3-4Yy.png
    - assets/page-1/images/material-symbols-home-9aR.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-TS1.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1641-2-Wp1.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-4.png
    - assets/page-1/images/material-symbols-home-uS1.png
    - assets/page-1/images/line-8-d77.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-2F3.png
    - assets/page-1/images/material-symbols-wifi-WUy.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-3eZ.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-2Zf.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-MXF.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-Qdw.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-1.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-2.png
    - assets/page-1/images/ic-baseline-book-Em7.png
    - assets/page-1/images/material-symbols-search-rounded-5PP.png
    - assets/page-1/images/download-2-yLV.png
    - assets/page-1/images/ion-arrow-back-outline-9Y5.png
    - assets/page-1/images/line-6-rem.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-CdP.png
    - assets/page-1/images/ic-baseline-book-MYD.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-Jyf.png
    - assets/page-1/images/material-symbols-wifi-S7T.png
    - assets/page-1/images/ion-arrow-back-outline-eTj.png
    - assets/page-1/images/material-symbols-search-rounded-XnR.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-7ms.png
    - assets/page-1/images/material-symbols-search-rounded-UJD.png
    - assets/page-1/images/material-symbols-home-BZK.png
    - assets/page-1/images/whatsapp-image-2023-03-26-at-2120-1.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-L5P.png
    - assets/page-1/images/material-symbols-wifi-TwF.png
    - assets/page-1/images/material-symbols-wifi-AnM.png
    - assets/page-1/images/whatsapp-image-2023-03-26-at-2120-1-QDF.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-EzD.png
    - assets/page-1/images/material-symbols-wifi-BuT.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-JUH.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1622-3-3e9.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-2-52y.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-Tkm.png
    - assets/page-1/images/material-symbols-wifi-2Yq.png
    - assets/page-1/images/whatsappimage2023-04-07at2056-1.png
    - assets/page-1/images/ion-arrow-back-outline-wvZ.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-YaD.png
    - assets/page-1/images/mdi-password-BZB.png
    - assets/page-1/images/material-symbols-wifi-dC5.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-EBj.png
    - assets/page-1/images/mdi-user-circle-t3s.png
    - assets/page-1/images/whatsapp-image-2023-03-26-at-2120-2.png
    - assets/page-1/images/whatsapp-image-2023-03-26-at-2120-2-eQh.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-n7K.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-r6M.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-FpV.png
    - assets/page-1/images/ion-arrow-back-outline-Prh.png
    - assets/page-1/images/material-symbols-wifi-82V.png
    - assets/page-1/images/material-symbols-battery-horiz-075-sharp-fZs.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-bey.png
    - assets/page-1/images/material-symbols-wifi-zTB.png
    - assets/page-1/images/ion-arrow-back-outline-EsK.png
    - assets/page-1/images/whatsapp-image-2023-03-12-at-1639-1-zh7.png
    - assets/page-1/images/whatsapp-image-2023-03-17-at-2051-1-SLq.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
